### ISSUE TITLE
Disparity between SwooleEmitter and SapiEmitters?

### ISSUE THREAD

**Issue by mindplay-dk** [narrowspark/http-emitter#13]
I think there may be a slight disparity between `SwooleEmitter` and the SAPI emitters.

In terms of dependency injection, all emitters are behind `EmitterInterface`, which is good.

But the `SwooleEmitter` has a constructor-dependency on `SwooleResponse`, which implies a different life-cycle - whereas the SAPI emitters can be safely reused across multiple requests, the Swoole emitter (being designed for use in long-running apps) needs to be recreated for every request.

You may have intended for all emitters to be created and then destroyed for every request?

But it's not necessary, and it doesn't really seem to provide any benefit.

Of course, I could just ignore the interface and register them as separate components with explicit dependencies on the implementations - which might make sense anyway, since the Swoole emitter has implicit dependency on Swoole and an event-loop and so on.

I wonder if the interface is actually meaningful or just misleading?

You can't actually plug a Swoole emitter into a normal stack and get something that works - similarly, you can't plug a SAPI emitter into a Swoole-based stack and get something that works.

The interface seems to imply a some kind of meaninful of abstraction, but... is it meaningful?

If not, perhaps we might consider a simpler abstraction that treats the emitters as an implementation detail, and instead provides a higher-level "host" abstraction based on PSR-15 handlers:

```php
use Psr\Http\Server\RequestHandlerInterface;

interface Host
{
    public function run(RequestHandlerInterface $handler): void;
}
```

With this abstraction, a `SapiHost` would run the `$handler` once (e.g. from an `index.php` script) while the `SwooleHost` would actually implement the event-loop and dispatch the `$handler` repeatedly; something that's currently left up to the consumer.

Also missing from this package is something to convert from a Swoole Request to a PSR-7 Request - this could be built into the Swoole host as well.

Thoughts?

**Comment by mindplay-dk** [comment]
PSR-15 `RequestHandlerInterface` might be an obvious choice for a common interface for these "hosts" - if so, some middleware-stacks might even permit you to simply plug this in as the "final" handler after the middleware-stack.

**Comment by mindplay-dk** [comment]
> PSR-15 `RequestHandlerInterface` might be an obvious choice for a common interface for these "hosts" - if so, some middleware-stacks might even permit you to simply plug this in as the "final" handler after the middleware-stack.

In hindsight, this sounds completely wrong to me now.

Having thought more about this, I don't think these "hosts" need to implement a common interface, at all. The only abstraction we need is already there - it's `RequestHandlerInterface`.

A SAPI host and a Swoole host don't have the same behavior, same use-cases or same life-cycle - nothing is won by making them implement the same interface, because that doesn't make them interchangeable in the first place.

For example, a SAPI host is used in an `index.php` and processes a single request, whereas a Swoole host is used from a CLI script and processes many request.

Any type of host can accept a `RequestHandlerInterface` instance via the constructor, which completely addresses the problem, since "request handlers", obviously, handle the requests, while creating the request, and emitting the response, are both completely implementation-specific to the hosts.

Make sense?

**Comment by prisis** [comment]
Yeah, my plan is to remove the interface and the hole swoole class from this package

**Comment by mindplay-dk** [comment]
Is there any particular reason why we need two SAPI emitters to begin with?

I'm working on PSR-15/17 integration and I'd like to just refactor the whole thing to a single class - there's really no point in having more than one dependency for something that performs a single function.

So usage from `index.php` will look like this:

```php
$host = new SAPIHost(
    $serverRequestFactory, // ServerRequestFactoryInterface
    $uriFactory,           // UriFactoryInterface
    $uploadedFileFactory,  // UploadedFileFactoryInterface
    $streamFactory,        // StreamFactoryInterface
    $responseFactory       // ReaponseFactoryInterface
);

$host->dispatch($handler); // where $handler is HandlerInterface (PSR-15)
```

There's really no point in even having an instance, since you will run this once from `index.php` and it will modify global state, but... I'll keep it as an instance, for the sake of testing at least, and since it will have dependencies on the PSR-17 factories.

(I will completely understand if this change is too drastic - if you don't want to merge this when it's done, I'll just fork the project, no problem. I'll let you take a look and decide first though...)
