### ISSUE TITLE
Multi-byte string assumption in SapiStreamEmitter::emitBodyRange() ?

### ISSUE THREAD

**Issue by mindplay-dk** [narrowspark/http-emitter#14]
Are you deliberately using multi-byte string functions to deal with ranged emits?

Looks like you referenced [zend](https://github.com/zendframework/zend-httphandlerrunner/blob/master/src/Emitter/SapiStreamEmitter.php#L79-L110) for this bit?

If they were using multi-byte functions at the time, they've since corrected this.

The `Content-Range` header specified *bytes*, not character points - so this looks like a bug, and likely a missing test-case to prove that emitting binary data actually works?

**Comment by prisis** [comment]
So i check `Content-Range` draft https://tools.ietf.org/html/draft-ietf-http-range-retrieval-00, https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35 and https://stackoverflow.com/questions/2209204/parsing-http-range-header-in-php and didnt find any bug, i have some test for this cases https://github.com/narrowspark/http-emitter/blob/bfad1b2255a5012a5602bd1c2835e8e60e49cce4/tests/SapiStreamEmitterTest.php#L554, https://github.com/narrowspark/http-emitter/blob/bfad1b2255a5012a5602bd1c2835e8e60e49cce4/tests/SapiStreamEmitterTest.php#L566, https://github.com/narrowspark/http-emitter/blob/bfad1b2255a5012a5602bd1c2835e8e60e49cce4/tests/SapiStreamEmitterTest.php#L256 and https://github.com/narrowspark/http-emitter/blob/bfad1b2255a5012a5602bd1c2835e8e60e49cce4/tests/SapiStreamEmitterTest.php#L374

But is the only code that use the multi-byte functions, so i will change it to lose the dependency of mb-string

**Comment by mindplay-dk** [comment]
Yes, the assertions are all wrong as well, using the `mb_` functions.

I tried to write a regression test, deliberately introducing non-unicode byte ranges like `\xe2\x28\xa1\xc3\x28` and correcting the assertions to use non-`mb_` string functions, but I wasn't able to break it, because, well...

> I need to check if zend has more tests for this cases so i will add it

I'm not sure their test-cases are very good?

For example, I'm not convinced that `testEmitRangeStreamResponse` is actually testing anything meaningful - all of the `$content` strings defined in `emitRangeStreamResponseProvider` are too short to hit any of the edge-cases where introducing non-unicode bytes in the content would return the wrong length.

So a "successful" regression-test would be my first move - I wanted to help, but I really can't find my way around these tests, sorry...

**Comment by mindplay-dk** [comment]
Lets at least patch this up so we can start using this package?

The regression test would be a boon, but zend's package doesn't have anything like that either, so maybe it's not necessary?

(btw, just curious, how did this happen in the first place? did you decide to make this change, or was this is the work of some tool that tries to enforce "best practices" across the board? just wondering.)

**Comment by prisis** [comment]
This is a cs-fixer config, that I need to change

**Comment by mindplay-dk** [comment]
With these bugfixes in place, do you think you could publish a release?

I want to set the next version as the minimum required by our project before we switch to this package :-)

**Comment by prisis** [comment]
Yes :), need just to generate the changelog, will do it asap

**Comment by prisis** [comment]
@mindplay-dk tag is out :)

**Comment by mindplay-dk** [comment]
@prisis thanks :-)

You can close this issue unless you care about adding that regression-test at some point.

(Personally I'm fine either way. I trust this works.)

**Comment by prisis** [comment]
I will use this as a reminder, maybe I can write some test on the weekend

**Comment by burzum** [comment]
@prisis any news on this? It's over one year open. :(

**Comment by prisis** [comment]
@burzum This ticket is just a reminder to write the missing tests and I didn't find a way to break it, the fix with the removing of the mb functions is out for a long time, what are you missing?

**Comment by prisis** [comment]
Didn't find test that did break for this use case...
