### ISSUE TITLE
Don't stream the entire response into memory

### ISSUE THREAD

**Issue by Nemo64** [narrowspark/http-emitter#23]
Currently, the entire body is streamed into memory before being emitted.
https://github.com/narrowspark/http-emitter/blob/master/src/SapiEmitter.php#L33

The response body can get very large, so I would prefer a "streamy" approach.

```PHP
$stream = $response->getBody();
$stream->rewind();
while (!$stream->eof()) {
    echo $stream->read(1048576); // read in 1MB steps
}
```

**Comment by Nemo64** [comment]
Now that I think of it, you actually need the request to emit the response correctly.

1. To implement Content-Range
2. To respect something like etags if-modified-since etc.

It is a lot more complex to create a complete implementation.

**Comment by prisis** [comment]
Did you see the stream emitter?

**Comment by Nemo64** [comment]
Ohh, I didn't. Sorry.
