### ISSUE TITLE
Update composer.json to make it work with PHP8

### ISSUE THREAD

**Issue by burzum** [narrowspark/http-emitter#45]
The error I'm getting:
> narrowspark/http-emitter 0.8.0 requires php ^7.1 -> your php version (8.0.6) does not satisfy that requirement.

**Comment by prisis** [comment]
Hey, you need to upgrade the package version to ^2.0.0 :)

**Comment by floriankraemer** [comment]
Well, I need to support PHP  7 and 8. :( The older version should run without problems on PHP 8.

**Comment by prisis** [comment]
@floriankraemer did you try "^1 || ^2", it didnt change much between this versions, check the changelog file :)
